[[constraint]]
  version = ">=0.14.0"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = ">=0.14.0"
  name = "github.com/pulumi/pulumi-aws"

[prune]
  go-tests = true
  unused-packages = true
